# Face ID project

### Haar Cascades

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

def showImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

def showGrayScaleImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(img, cmap='gray')

all_contours = -1
green = (0,255,0)
thickness = 2

new_img = cv2.UMat(cv2.IMREAD_COLOR)


#####################################3

image_template = []

image_template.append(cv2.imread('img/eva.jpg')) 
image_template.append(cv2.imread('img/edgar.jpg'))
#for i in range(len(image_template)):
 #   showImg(image_template[i])
    
####################################3

def ORB_detector(new_image, image_template):
    # Function that compares input image to template
    # It then returns the number of ORB matches between them
    
    image1 = cv2.cvtColor(new_image, cv2.COLOR_BGR2GRAY)
    
    #showImg(image1)
    
    # Create ORB detector with 1000 keypoints with a scaling pyramid factor of 1.2
    orb = cv2.ORB_create(1000, 1.2)
    
    # Detect keypoints of original image
    (kp1, des1) = orb.detectAndCompute(image1, None)

    # Detect keypoints of rotated image
    (kp2, des2) = orb.detectAndCompute(image_template, None)

    # Create matcher     
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)

    # Do matching
    matches = bf.match(des1,des2)

    # Sort the matches based on distance.  Least distance
    # is better
    matches = sorted(matches, key=lambda val: val.distance)
    
    if len(matches) > 210:
        matches_img = cv2.drawMatches(image1,kp1,image_template,kp2,matches[:20],None)
        cv2.imwrite('orbMatches.jpg',matches_img)

    return matches

#################################################






In [3]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)

while True:

    # Get webcam images
    ret, frame = cap.read()

    height, width = frame.shape[:2]

    top_left_x = width // 3
    top_left_y = (height // 2) + (height // 4)
    bottom_right_x = (width // 3) * 2
    bottom_right_y = (height // 2) - (height // 4)

    faces = face_classifier.detectMultiScale(frame, 1.3, 5)
    print(faces)
    
    people_values =[]
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (127,0,255), 2)
    
        magin = 30
        top_left_x = x-magin
        top_left_y = y-magin
        bottom_right_x = x+w+magin
        bottom_right_y = y+h+magin
    

        cropped = frame[top_left_y:bottom_right_y, top_left_x:bottom_right_x]
        print(len(faces))
        print((cropped))
        # Repasa todas las caras 
        for i in range(len(image_template)):
            matches = ORB_detector(cropped, image_template[i])
            
            people_values.append(matches)

        threshold = 150

        # If matches exceed our threshold then object has been detected
        for i in range(len(image_template)):
            
            if len(people_values[i]) > threshold:
                #frame = frame.copy()
                if i == 0:
                    text = "Eva "+str(len(people_values[i]))
                    #cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
                    cv2.putText(frame,text,(int(top_left_x+w/2),top_left_y-20), cv2.FONT_HERSHEY_COMPLEX, 1 ,(127,0,255), 2) 

                elif i == 1:
                    text = "Edgar "+str(len(people_values[i]))
                    #cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
                    cv2.putText(frame,text,(int(top_left_x+w/2),top_left_y+10), cv2.FONT_HERSHEY_COMPLEX, 1 ,(127,0,255), 2) 

                
                
        # Flip frame orientation horizontally
  #  frame = cv2.flip(frame,1)
            
    cv2.imshow('Object Detector using ORB', frame)
    
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[283 178 261 261]]
1
[[[ 91 106 104]
  [ 91 107 105]
  [ 91 107 105]
  ...
  [101 113 106]
  [103 112 106]
  [102 111 105]]

 [[ 88 102 100]
  [ 89 104 101]
  [ 89 104 101]
  ...
  [103 114 107]
  [101 113 106]
  [101 113 106]]

 [[ 85  99  97]
  [ 85  99  97]
  [ 85  99  97]
  ...
  [107 116 110]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 43  50  49]
  [ 43  50  49]
  [ 42  49  48]
  ...
  [181 179 152]
  [180 178 151]
  [179 177 150]]

 [[ 45  50  49]
  [ 45  50  49]
  [ 44  49  48]
  ...
  [184 181 154]
  [182 180 153]
  [181 179 152]]

 [[ 42  49  48]
  [ 42  49  48]
  [ 42  49  48]
  ...
  [186 185 153]
  [190 186 159]
  [190 186 159]]]
[[289 179 251 251]]
1
[[[ 94 104 102]
  [ 91 106 104]
  [ 93 107 105]
  ...
  [105 116 110]
  [105 116 110]
  [106 117 111]]

 [[ 87 101  99]
  [ 87 101  99]
  [ 87 101  99]
  ...
  [105 114 113]
  [107 114 113]
  [106 113 112]]

 [[ 85  99  97]
  [ 82  99  97]
  [ 82  99  97]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 ...

 [[ 47  

[[251 146 280 280]]
1
[[[ 82  97  94]
  [ 80  97  94]
  [ 81  98  95]
  ...
  [104 115 109]
  [104 115 109]
  [106 115 109]]

 [[ 80  94  92]
  [ 80  94  92]
  [ 81  95  93]
  ...
  [104 116 107]
  [104 116 107]
  [104 115 109]]

 [[ 84  94  92]
  [ 77  94  91]
  [ 78  95  92]
  ...
  [104 116 107]
  [104 116 107]
  [104 115 109]]

 ...

 [[ 47  56  55]
  [ 44  54  52]
  [ 42  52  50]
  ...
  [ 88  82  67]
  [ 86  79  64]
  [ 87  81  66]]

 [[ 47  56  55]
  [ 45  52  51]
  [ 44  51  50]
  ...
  [ 86  79  64]
  [ 86  79  64]
  [ 86  80  63]]

 [[ 47  56  55]
  [ 42  52  50]
  [ 41  50  49]
  ...
  [ 86  79  64]
  [ 86  79  64]
  [ 79  79  61]]]
[[247 150 270 270]]
1
[[[ 92 102 100]
  [ 92 102 100]
  [ 91 101  99]
  ...
  [105 114 106]
  [105 114 106]
  [106 115 107]]

 [[ 94 104 102]
  [ 93 103 101]
  [ 93 103 101]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 107]]

 [[ 96 105 104]
  [ 96 105 104]
  [ 96 105 104]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 ...

 [[ 51  

[[263 156 249 249]]
1
[[[105 114 113]
  [105 114 115]
  [106 115 116]
  ...
  [108 115 114]
  [108 117 111]
  [108 117 111]]

 [[106 115 116]
  [106 115 116]
  [106 115 116]
  ...
  [109 116 115]
  [108 115 114]
  [108 115 114]]

 [[106 116 114]
  [106 116 114]
  [106 116 114]
  ...
  [109 116 115]
  [111 116 115]
  [111 116 115]]

 ...

 [[ 47  55  54]
  [ 47  55  54]
  [ 47  55  54]
  ...
  [216 206 176]
  [207 196 166]
  [206 195 165]]

 [[ 46  54  52]
  [ 47  55  54]
  [ 46  54  52]
  ...
  [205 202 171]
  [203 199 177]
  [214 210 188]]

 [[ 45  54  48]
  [ 45  52  51]
  [ 45  52  51]
  ...
  [232 232 219]
  [235 235 219]
  [235 235 219]]]
[[264 159 249 249]]
1
[[[108 115 114]
  [108 115 114]
  [106 116 114]
  ...
  [108 117 111]
  [108 117 111]
  [108 115 114]]

 [[108 115 114]
  [108 115 114]
  [106 116 114]
  ...
  [108 115 114]
  [108 115 114]
  [108 115 114]]

 [[106 116 114]
  [106 116 114]
  [106 116 114]
  ...
  [108 117 111]
  [108 117 111]
  [108 115 114]]

 ...

 [[ 46  

[[244 145 275 275]]
1
[[[ 78  94  86]
  [ 78  94  86]
  [ 78  94  85]
  ...
  [106 113 112]
  [106 113 112]
  [108 113 112]]

 [[ 80  96  89]
  [ 80  96  89]
  [ 78  96  89]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 82  98  91]
  [ 82  98  91]
  [ 82  97  94]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 ...

 [[ 51  65  70]
  [ 49  63  68]
  [ 51  64  66]
  ...
  [ 91  83  66]
  [ 91  83  66]
  [ 93  83  66]]

 [[ 49  63  68]
  [ 49  63  68]
  [ 50  62  65]
  ...
  [ 91  85  63]
  [ 90  84  62]
  [ 90  84  62]]

 [[ 51  64  66]
  [ 50  62  65]
  [ 48  62  62]
  ...
  [ 89  81  64]
  [ 89  81  64]
  [ 89  83  61]]]
[[243 143 276 276]]
1
[[[ 82  98  91]
  [ 82  98  91]
  [ 81  97  90]
  ...
  [105 113 107]
  [105 113 107]
  [105 113 107]]

 [[ 78  94  85]
  [ 83  94  88]
  [ 83  94  88]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 83  94  88]
  [ 83  95  86]
  [ 83  95  86]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 107]]

 ...

 [[ 52  

[[259 154 247 247]]
1
[[[106 116 114]
  [106 116 114]
  [106 116 114]
  ...
  [109 116 115]
  [109 116 115]
  [108 115 114]]

 [[109 116 115]
  [109 116 115]
  [108 115 114]
  ...
  [109 116 115]
  [111 116 115]
  [111 116 115]]

 [[109 116 115]
  [109 116 115]
  [109 116 115]
  ...
  [111 116 115]
  [112 117 116]
  [111 116 115]]

 ...

 [[ 46  51  50]
  [ 44  51  50]
  [ 44  51  50]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 46  51  50]
  [ 46  51  50]
  [ 46  51  50]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 46  51  50]
  [ 44  51  50]
  [ 44  51  50]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]]
[[259 150 253 253]]
1
[[[105 114 113]
  [101 115 113]
  [101 115 113]
  ...
  [108 115 114]
  [108 117 111]
  [108 117 111]]

 [[102 116 114]
  [102 118 111]
  [102 118 111]
  ...
  [110 115 114]
  [108 115 114]
  [108 115 114]]

 [[102 116 114]
  [106 116 114]
  [106 116 114]
  ...
  [108 115 114]
  [108 115 114]
  [108 115 114]]

 ...

 [[ 44  

[[245 146 271 271]]
1
[[[ 99 109 107]
  [ 99 109 107]
  [100 110 108]
  ...
  [107 116 110]
  [105 116 110]
  [104 115 109]]

 [[ 99 109 107]
  [101 111 109]
  [101 111 109]
  ...
  [107 116 110]
  [105 116 110]
  [105 116 110]]

 [[101 111 109]
  [103 112 111]
  [103 112 111]
  ...
  [106 116 114]
  [105 116 110]
  [105 116 110]]

 ...

 [[ 51  63  68]
  [ 50  59  60]
  [ 47  55  56]
  ...
  [ 89  83  68]
  [ 91  83  66]
  [ 91  83  66]]

 [[ 48  61  64]
  [ 50  60  58]
  [ 45  55  54]
  ...
  [ 89  83  68]
  [ 88  83  65]
  [ 88  83  65]]

 [[ 51  59  63]
  [ 51  57  59]
  [ 49  55  56]
  ...
  [ 89  84  66]
  [ 90  82  65]
  [ 90  82  65]]]
[[248 145 267 267]]
1
[[[ 97 106 105]
  [ 98 107 106]
  [ 98 107 106]
  ...
  [104 113 112]
  [104 113 112]
  [104 113 112]]

 [[ 96 111 108]
  [ 95 109 107]
  [ 96 111 108]
  ...
  [104 113 112]
  [104 113 112]
  [106 115 109]]

 [[101 111 109]
  [101 111 109]
  [101 111 109]
  ...
  [104 113 112]
  [104 113 112]
  [104 113 112]]

 ...

 [[ 42  

[[246 148 272 272]]
1
[[[ 94 104 102]
  [ 99 109 107]
  [100 110 108]
  ...
  [106 115 109]
  [107 116 110]
  [106 115 109]]

 [[ 98 107 106]
  [100 110 108]
  [101 111 109]
  ...
  [107 116 110]
  [107 116 110]
  [106 115 109]]

 [[ 98 107 106]
  [100 110 108]
  [103 112 111]
  ...
  [107 114 113]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 56  63  69]
  [ 55  62  68]
  [ 50  59  60]
  ...
  [ 89  83  68]
  [ 91  82  68]
  [ 91  82  68]]

 [[ 56  63  69]
  [ 54  61  66]
  [ 49  58  59]
  ...
  [ 88  81  68]
  [ 90  81  67]
  [ 90  81  67]]

 [[ 52  60  64]
  [ 50  58  61]
  [ 50  57  56]
  ...
  [ 88  82  67]
  [ 89  80  66]
  [ 90  81  67]]]
[[245 145 274 274]]
1
[[[ 87 104 101]
  [ 87 104 101]
  [ 88 105 102]
  ...
  [104 115 109]
  [104 115 109]
  [104 115 109]]

 [[ 87 104 101]
  [ 88 105 102]
  [ 92 109 106]
  ...
  [106 113 112]
  [106 113 112]
  [106 115 109]]

 [[ 89 104 101]
  [ 91 106 104]
  [ 95 109 107]
  ...
  [105 116 110]
  [105 116 110]
  [105 116 110]]

 ...

 [[ 58  

  [ 89  84  66]]]
[[236 140 282 282]]
1
[[[ 80  96  89]
  [ 80  96  89]
  [ 80  97  87]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 85  96  90]
  [ 86  97  91]
  [ 85  95  93]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 91 101  99]
  [ 91 101  99]
  [ 91 101  99]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 ...

 [[ 54  66  71]
  [ 53  65  70]
  [ 51  63  68]
  ...
  [ 88  86  70]
  [ 92  85  70]
  [ 92  85  70]]

 [[ 54  66  71]
  [ 50  62  66]
  [ 48  60  65]
  ...
  [ 92  91  73]
  [ 90  89  71]
  [ 90  89  71]]

 [[ 54  66  71]
  [ 51  63  68]
  [ 47  59  64]
  ...
  [ 84  83  67]
  [ 79  78  62]
  [ 78  77  61]]]
[[240 140 281 281]]
1
[[[ 80  98  86]
  [ 80  98  86]
  [ 80  94  92]
  ...
  [106 115 109]
  [106 115 109]
  [103 114 107]]

 [[ 83  99  92]
  [ 82  98  91]
  [ 86  97  91]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 89 105  98]
  [ 88 104  97]
  [ 87 101  99]
  ...
  [106 115 109]
  [106 115 109]
  [104 116 107

[[240 139 281 281]]
1
[[[ 86  96  94]
  [ 86  96  94]
  [ 82  97  94]
  ...
  [103 111 109]
  [103 111 109]
  [105 113 107]]

 [[ 82  93  86]
  [ 82  93  86]
  [ 78  92  90]
  ...
  [107 113 107]
  [107 113 107]
  [106 115 109]]

 [[ 83  92  91]
  [ 83  92  91]
  [ 83  92  91]
  ...
  [108 114 109]
  [108 114 109]
  [106 115 109]]

 ...

 [[ 59  68  81]
  [ 58  67  79]
  [ 57  67  77]
  ...
  [ 88  83  65]
  [ 88  83  65]
  [ 86  82  60]]

 [[ 58  70  75]
  [ 58  70  75]
  [ 55  67  72]
  ...
  [ 87  81  64]
  [ 87  81  64]
  [ 87  83  61]]

 [[ 57  69  73]
  [ 55  67  72]
  [ 51  63  68]
  ...
  [ 88  83  65]
  [ 88  83  65]
  [ 88  83  65]]]
[[250 146 268 268]]
1
[[[ 96 111 108]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [107 116 110]
  [106 115 109]
  [106 115 109]]

 [[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [107 114 113]
  [107 116 110]
  [107 116 110]]

 [[ 97 112 109]
  [ 98 113 111]
  [ 97 112 109]
  ...
  [105 114 113]
  [105 114 113]
  [105 114 113]]

 ...

 [[ 50  

[[248 148 278 278]]
1
[[[ 97 106 105]
  [ 99 109 107]
  [100 110 108]
  ...
  [108 115 114]
  [110 115 114]
  [110 115 114]]

 [[ 97 106 105]
  [101 111 109]
  [103 112 111]
  ...
  [110 115 114]
  [110 115 114]
  [110 115 114]]

 [[ 99 109 107]
  [101 111 109]
  [103 112 111]
  ...
  [108 115 114]
  [110 115 114]
  [110 115 114]]

 ...

 [[ 48  56  59]
  [ 48  56  59]
  [ 47  56  55]
  ...
  [ 88  88  66]
  [ 95  91  69]
  [ 95  91  69]]

 [[ 48  57  57]
  [ 48  57  57]
  [ 45  55  54]
  ...
  [ 94  88  71]
  [103  98  80]
  [102  97  79]]

 [[ 45  54  55]
  [ 45  54  55]
  [ 46  54  52]
  ...
  [102  95  74]
  [103  97  73]
  [104  99  74]]]
[[241 142 288 288]]
1
[[[ 80  96  89]
  [ 81  97  90]
  [ 81  97  90]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 89  98  97]
  [ 89  98  97]
  [ 89  98  97]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 94 106  99]
  [ 93 103 101]
  [ 93 103 101]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 52  

[[246 147 278 278]]
1
[[[ 91 105 105]
  [ 91 105 105]
  [ 91 105 105]
  ...
  [109 114 113]
  [109 114 113]
  [109 114 113]]

 [[ 93 107 105]
  [ 93 107 105]
  [ 91 106 104]
  ...
  [109 115 110]
  [109 116 108]
  [109 116 108]]

 [[ 97 106 105]
  [ 97 106 105]
  [ 97 106 105]
  ...
  [109 115 110]
  [110 116 111]
  [110 116 111]]

 ...

 [[ 51  61  59]
  [ 49  59  57]
  [ 48  57  56]
  ...
  [ 86  86  68]
  [ 85  84  66]
  [ 84  83  65]]

 [[ 48  57  56]
  [ 47  56  55]
  [ 47  56  55]
  ...
  [ 92  93  70]
  [ 89  88  70]
  [ 86  86  68]]

 [[ 45  55  54]
  [ 47  56  55]
  [ 47  56  55]
  ...
  [104 100  78]
  [ 97  93  71]
  [ 94  90  68]]]
[[250 144 276 276]]
1
[[[ 90 105 102]
  [ 91 106 104]
  [ 93 107 105]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 93 107 105]
  [ 95 109 107]
  [ 95 109 107]
  ...
  [107 116 110]
  [106 113 112]
  [106 113 112]]

 [[ 93 107 105]
  [ 95 109 107]
  [ 97 112 109]
  ...
  [106 115 109]
  [108 114 109]
  [109 115 110]]

 ...

 [[ 54  

[[247 146 270 270]]
1
[[[ 96 105 104]
  [ 99 109 107]
  [ 99 109 107]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 97 106 105]
  [100 110 108]
  [101 111 109]
  ...
  [107 116 110]
  [107 116 110]
  [107 116 110]]

 [[ 97 106 105]
  [103 111 109]
  [103 111 109]
  ...
  [109 116 108]
  [109 116 108]
  [107 116 110]]

 ...

 [[ 47  60  63]
  [ 50  59  60]
  [ 48  57  57]
  ...
  [ 98  88  71]
  [ 98  88  71]
  [ 97  86  71]]

 [[ 46  60  60]
  [ 46  60  60]
  [ 44  57  57]
  ...
  [ 94  87  66]
  [ 94  87  66]
  [ 94  86  64]]

 [[ 46  60  60]
  [ 46  61  58]
  [ 44  58  56]
  ...
  [ 92  84  68]
  [ 92  84  68]
  [ 92  84  68]]]
[[240 141 281 281]]
1
[[[ 85  92  91]
  [ 85  92  91]
  [ 84  95  89]
  ...
  [104 116 107]
  [104 116 107]
  [104 116 107]]

 [[ 84  95  89]
  [ 84  95  89]
  [ 85  96  90]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 92  99  98]
  [ 91  98  97]
  [ 90  99  98]
  ...
  [106 115 107]
  [106 115 107]
  [104 116 107]]

 ...

 [[ 52  

[[248 145 274 274]]
1
[[[ 91 108 100]
  [ 93 109 102]
  [ 95 111 104]
  ...
  [106 113 112]
  [108 114 109]
  [109 115 110]]

 [[ 93 109 102]
  [ 94 110 103]
  [ 95 109 107]
  ...
  [106 115 109]
  [106 115 109]
  [107 116 110]]

 [[ 93 109 102]
  [ 95 111 104]
  [ 96 111 108]
  ...
  [106 115 109]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 50  59  60]
  [ 50  59  60]
  [ 50  56  57]
  ...
  [ 91  83  66]
  [ 91  82  70]
  [ 91  82  70]]

 [[ 49  58  59]
  [ 49  58  59]
  [ 50  56  57]
  ...
  [ 90  82  65]
  [ 88  82  67]
  [ 88  82  67]]

 [[ 49  59  57]
  [ 48  57  56]
  [ 48  57  56]
  ...
  [ 86  79  64]
  [ 88  78  66]
  [ 88  78  66]]]
[[245 144 275 275]]
1
[[[ 89 104 101]
  [ 94 104 102]
  [ 93 103 101]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 [[ 97 106 105]
  [ 97 106 105]
  [ 97 106 105]
  ...
  [106 115 109]
  [106 113 112]
  [106 113 112]]

 [[100 107 106]
  [ 96 105 104]
  [ 96 105 104]
  ...
  [106 115 109]
  [107 114 113]
  [106 113 112]]

 ...

 [[ 52  

[[255 142 270 270]]
1
[[[ 96 111 108]
  [ 96 111 108]
  [ 96 111 108]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 [[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [106 115 109]
  [106 115 109]
  [108 114 109]]

 [[ 97 112 109]
  [ 98 113 111]
  [ 97 112 109]
  ...
  [106 115 109]
  [106 115 109]
  [108 114 109]]

 ...

 [[ 43  52  46]
  [ 45  50  49]
  [ 45  50  49]
  ...
  [114  99  77]
  [114  99  77]
  [114  99  77]]

 [[ 45  50  49]
  [ 42  49  48]
  [ 42  49  48]
  ...
  [103  94  73]
  [103  94  73]
  [105  93  70]]

 [[ 42  49  48]
  [ 42  51  45]
  [ 42  51  45]
  ...
  [100  92  70]
  [ 99  90  69]
  [ 98  89  68]]]
[[254 143 270 270]]
1
[[[ 95 112 109]
  [ 95 112 109]
  [ 97 112 109]
  ...
  [108 113 112]
  [104 113 112]
  [104 113 112]]

 [[ 96 113 111]
  [ 95 112 109]
  [ 95 111 111]
  ...
  [106 115 107]
  [106 115 109]
  [107 116 110]]

 [[ 98 113 111]
  [ 98 113 111]
  [ 98 113 111]
  ...
  [106 115 109]
  [106 115 109]
  [107 116 110]]

 ...

 [[ 43  

[[258 146 263 263]]
1
[[[104 113 112]
  [104 113 112]
  [104 113 112]
  ...
  [110 116 111]
  [109 115 110]
  [109 115 110]]

 [[104 113 112]
  [105 114 113]
  [107 114 113]
  ...
  [110 116 111]
  [109 115 110]
  [109 115 110]]

 [[105 114 113]
  [105 114 113]
  [105 114 113]
  ...
  [110 117 109]
  [109 116 108]
  [108 117 111]]

 ...

 [[ 42  51  43]
  [ 42  51  43]
  [ 41  50  42]
  ...
  [117 102  79]
  [116 100  78]
  [118  99  79]]

 [[ 42  51  45]
  [ 42  51  45]
  [ 41  49  43]
  ...
  [117 102  79]
  [117 102  79]
  [119 101  79]]

 [[ 42  51  45]
  [ 42  51  45]
  [ 42  51  45]
  ...
  [109  93  73]
  [109  93  73]
  [109  93  71]]]
[[250 140 274 274]]
1
[[[ 93 107 105]
  [ 93 107 105]
  [ 93 107 105]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 98 107 106]
  [ 99 109 107]
  [ 95 109 107]
  ...
  [106 115 107]
  [106 115 109]
  [106 115 109]]

 [[ 99 109 107]
  [101 111 109]
  [101 111 109]
  ...
  [108 114 109]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 52  

[[255 146 263 263]]
1
[[[101 110 111]
  [ 97 111 111]
  [ 97 111 111]
  ...
  [106 116 105]
  [106 115 107]
  [106 115 107]]

 [[ 98 112 112]
  [ 98 112 112]
  [100 113 113]
  ...
  [107 117 108]
  [106 115 109]
  [107 116 110]]

 [[104 112 113]
  [100 114 112]
  [100 114 112]
  ...
  [105 116 110]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 40  52  43]
  [ 42  51  43]
  [ 43  52  44]
  ...
  [241 227 222]
  [239 224 220]
  [236 222 218]]

 [[ 42  51  43]
  [ 42  51  45]
  [ 42  51  45]
  ...
  [150 132 112]
  [147 128 109]
  [144 126 106]]

 [[ 40  51  45]
  [ 42  51  45]
  [ 42  51  45]
  ...
  [123 102  92]
  [123 102  92]
  [123 102  92]]]
[[261 153 251 251]]
1
[[[102 116 114]
  [102 116 114]
  [102 116 114]
  ...
  [108 117 111]
  [108 117 111]
  [108 117 111]]

 [[102 116 114]
  [102 116 114]
  [102 116 114]
  ...
  [108 117 111]
  [108 117 111]
  [108 117 111]]

 [[106 116 114]
  [106 116 114]
  [106 116 114]
  ...
  [109 116 115]
  [108 117 111]
  [108 117 111]]

 ...

 [[ 44  

[[252 143 269 269]]
1
[[[ 91 107 105]
  [ 91 107 105]
  [ 92 109 106]
  ...
  [108 114 109]
  [108 114 109]
  [106 115 109]]

 [[ 93 110 107]
  [ 93 110 107]
  [ 96 111 108]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [106 115 109]
  [106 115 109]
  [108 114 109]]

 ...

 [[ 43  53  51]
  [ 43  53  51]
  [ 42  51  45]
  ...
  [117 105  80]
  [117 105  80]
  [115 108  82]]

 [[ 45  54  48]
  [ 44  53  47]
  [ 43  52  46]
  ...
  [107  97  80]
  [108  98  82]
  [108 100  78]]

 [[ 47  55  54]
  [ 44  51  50]
  [ 42  51  45]
  ...
  [101  93  71]
  [101  93  71]
  [ 97  93  71]]]
[[250 143 269 269]]
1
[[[ 96 105 104]
  [ 97 106 105]
  [ 97 106 105]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 107]]

 [[ 97 106 105]
  [ 98 107 106]
  [ 98 107 106]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 107]]

 [[ 96 105 104]
  [ 99 109 107]
  [101 111 109]
  ...
  [109 116 108]
  [109 116 108]
  [108 115 107]]

 ...

 [[ 48  

[[251 139 275 275]]
1
[[[ 83  98  95]
  [ 80  97  94]
  [ 81  98  95]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 90 105 102]
  [ 91 106 104]
  [ 91 106 104]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 94 108 106]
  [ 94 108 106]
  [ 94 108 106]
  ...
  [106 113 112]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 49  58  59]
  [ 45  55  54]
  [ 42  52  50]
  ...
  [ 96  90  66]
  [ 96  90  68]
  [ 96  90  68]]

 [[ 48  57  57]
  [ 45  52  51]
  [ 44  51  50]
  ...
  [ 92  88  66]
  [ 90  85  68]
  [ 90  85  68]]

 [[ 48  57  57]
  [ 45  54  55]
  [ 42  51  52]
  ...
  [ 90  86  64]
  [ 85  84  66]
  [ 85  84  66]]]
[[250 138 278 278]]
1
[[[ 80  93  95]
  [ 81  94  96]
  [ 81  94  96]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 82  95  97]
  [ 83  96  99]
  [ 83  97  97]
  ...
  [108 114 109]
  [106 113 112]
  [106 113 112]]

 [[ 87 100 101]
  [ 89 103 103]
  [ 89 103 103]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 ...

 [[ 49  

[[255 143 266 266]]
1
[[[ 97 111 111]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [106 115 109]
  [106 115 109]
  [106 113 112]]

 [[101 111 109]
  [103 112 111]
  [103 112 111]
  ...
  [106 115 109]
  [107 116 110]
  [107 114 113]]

 [[104 113 112]
  [100 114 112]
  [100 114 112]
  ...
  [107 116 110]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 42  49  48]
  [ 42  51  43]
  [ 42  51  43]
  ...
  [119 102  86]
  [119 102  86]
  [118 100  85]]

 [[ 42  51  45]
  [ 42  51  45]
  [ 42  51  45]
  ...
  [123 107  86]
  [121 105  85]
  [121 105  85]]

 [[ 42  51  45]
  [ 42  51  43]
  [ 42  51  43]
  ...
  [106  98  74]
  [106  98  74]
  [110  97  74]]]
[[254 143 266 266]]
1
[[[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [108 115 107]
  [108 114 109]
  [108 114 109]]

 [[100 114 112]
  [ 98 113 111]
  [ 98 113 111]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 98 113 111]
  [100 114 112]
  [100 114 112]
  ...
  [107 117 108]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 41  

[[258 146 259 259]]
1
[[[100 114 112]
  [100 114 112]
  [100 114 112]
  ...
  [107 116 110]
  [107 116 110]
  [107 117 108]]

 [[100 114 112]
  [100 114 112]
  [100 116 109]
  ...
  [110 116 111]
  [110 116 111]
  [109 115 110]]

 [[105 114 113]
  [105 114 113]
  [101 115 113]
  ...
  [110 116 111]
  [110 116 111]
  [110 116 111]]

 ...

 [[ 43  50  49]
  [ 43  50  49]
  [ 43  50  49]
  ...
  [228 228 228]
  [228 228 228]
  [228 228 228]]

 [[ 45  50  49]
  [ 45  50  49]
  [ 45  50  49]
  ...
  [232 232 227]
  [232 232 227]
  [235 231 227]]

 [[ 42  49  48]
  [ 42  49  48]
  [ 43  50  49]
  ...
  [237 225 220]
  [236 224 219]
  [235 224 210]]]
[[261 148 252 252]]
1
[[[105 114 113]
  [104 113 112]
  [105 114 113]
  ...
  [110 117 109]
  [110 117 109]
  [108 117 111]]

 [[107 114 113]
  [105 114 113]
  [105 114 113]
  ...
  [108 117 111]
  [108 117 111]
  [108 118 109]]

 [[108 115 114]
  [106 116 114]
  [106 116 114]
  ...
  [108 117 111]
  [108 117 111]
  [106 117 111]]

 ...

 [[ 46  

[[247 141 276 276]]
1
[[[ 90 105 102]
  [ 90 105 102]
  [ 89 104 101]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 91 107 105]
  [ 91 107 105]
  [ 88 105 102]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 107]]

 [[ 91 107 105]
  [ 89 106 104]
  [ 89 106 104]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 51  63  68]
  [ 50  58  61]
  [ 49  57  60]
  ...
  [ 83  86  63]
  [ 83  86  63]
  [ 89  85  63]]

 [[ 44  58  63]
  [ 50  58  61]
  [ 48  56  59]
  ...
  [ 89  85  63]
  [ 89  85  63]
  [ 88  83  65]]

 [[ 45  58  60]
  [ 48  56  59]
  [ 48  56  59]
  ...
  [ 84  85  62]
  [ 84  85  62]
  [ 88  83  65]]]
[[245 138 283 283]]
1
[[[ 83  94  88]
  [ 83  97  81]
  [ 83  97  81]
  ...
  [108 115 107]
  [106 115 109]
  [105 113 107]]

 [[ 85  96  90]
  [ 84  96  87]
  [ 84  96  87]
  ...
  [106 115 109]
  [104 115 109]
  [104 115 109]]

 [[ 89 100  93]
  [ 87  99  92]
  [ 87  99  92]
  ...
  [108 115 107]
  [105 114 106]
  [106 115 107]]

 ...

 [[ 52  

[[245 139 277 277]]
1
[[[ 82  91  90]
  [ 82  91  90]
  [ 82  91  90]
  ...
  [105 113 107]
  [105 113 107]
  [106 115 109]]

 [[ 86  93  92]
  [ 86  93  92]
  [ 86  93  92]
  ...
  [103 114 107]
  [106 115 109]
  [106 115 109]]

 [[ 88  95  94]
  [ 86  96  94]
  [ 86  96  94]
  ...
  [104 115 109]
  [104 115 109]
  [104 115 109]]

 ...

 [[ 58  71  80]
  [ 57  69  73]
  [ 55  67  72]
  ...
  [ 98  89  68]
  [ 98  89  68]
  [ 98  89  68]]

 [[ 58  67  79]
  [ 57  67  77]
  [ 54  65  74]
  ...
  [ 96  85  69]
  [ 96  87  66]
  [ 96  87  66]]

 [[ 57  67  77]
  [ 57  69  73]
  [ 52  64  69]
  ...
  [ 94  87  66]
  [ 90  86  64]
  [ 89  85  63]]]
[[248 141 275 275]]
1
[[[ 82  98  91]
  [ 82  98  91]
  [ 86  97  91]
  ...
  [103 114 107]
  [103 114 107]
  [103 114 107]]

 [[ 92 102 100]
  [ 92 102 100]
  [ 90  99  98]
  ...
  [104 115 109]
  [104 115 109]
  [104 115 109]]

 [[ 93 103 101]
  [ 93 103 101]
  [ 93 104  98]
  ...
  [104 113 112]
  [104 113 112]
  [104 113 112]]

 ...

 [[ 58  

[[243 135 279 279]]
1
[[[ 89 105  98]
  [ 89 105  98]
  [ 89 105  98]
  ...
  [108 113 112]
  [108 113 112]
  [108 113 112]]

 [[ 84 102  95]
  [ 84 102  95]
  [ 82 101  93]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 79  97  90]
  [ 79  97  90]
  [ 79  97  90]
  ...
  [107 111 111]
  [105 112 111]
  [105 112 111]]

 ...

 [[ 57  67  77]
  [ 50  62  66]
  [ 48  60  65]
  ...
  [ 95  88  67]
  [ 95  88  67]
  [ 95  88  67]]

 [[ 50  64  69]
  [ 48  61  64]
  [ 48  61  64]
  ...
  [ 92  88  66]
  [ 92  86  64]
  [ 94  87  66]]

 [[ 50  62  66]
  [ 48  61  64]
  [ 46  59  61]
  ...
  [ 90  86  64]
  [ 90  85  68]
  [ 90  85  68]]]
[[246 139 274 274]]
1
[[[ 79  93  91]
  [ 79  93  91]
  [ 79  93  91]
  ...
  [105 113 107]
  [105 113 107]
  [105 113 107]]

 [[ 79  96  93]
  [ 80  97  94]
  [ 80  97  94]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 86 100  98]
  [ 86 100  98]
  [ 82  99  97]
  ...
  [108 114 109]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 47  

[[252 144 262 262]]
1
[[[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [107 114 113]
  [107 114 113]
  [106 113 112]]

 [[ 98 113 111]
  [ 98 113 111]
  [ 98 113 111]
  ...
  [107 116 110]
  [107 116 110]
  [107 116 110]]

 [[ 98 113 111]
  [100 114 112]
  [100 114 112]
  ...
  [108 117 111]
  [108 117 111]
  [107 116 110]]

 ...

 [[ 41  50  49]
  [ 41  50  49]
  [ 40  51  45]
  ...
  [235 231 227]
  [235 231 227]
  [235 231 227]]

 [[ 41  50  49]
  [ 40  49  48]
  [ 36  50  48]
  ...
  [229 221 204]
  [226 215 201]
  [221 210 196]]

 [[ 40  49  48]
  [ 40  49  48]
  [ 40  49  48]
  ...
  [147 125 115]
  [142 123 113]
  [141 122 111]]]
[[250 144 261 261]]
1
[[[ 96 110 110]
  [ 96 110 110]
  [ 97 112 109]
  ...
  [109 115 110]
  [109 115 110]
  [109 116 108]]

 [[100 110 108]
  [101 111 109]
  [ 98 113 111]
  ...
  [107 116 110]
  [107 116 110]
  [109 115 110]]

 [[ 97 112 109]
  [ 98 113 111]
  [100 114 112]
  ...
  [110 115 114]
  [109 114 113]
  [109 115 110]]

 ...

 [[ 42  

[[242 135 280 280]]
1
[[[ 90 105 102]
  [ 90 105 102]
  [ 89 104 101]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 [[ 85  99  97]
  [ 87 101  99]
  [ 86 100  98]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 [[ 82  97  94]
  [ 82  97  94]
  [ 82  96  96]
  ...
  [108 113 112]
  [105 112 111]
  [105 112 111]]

 ...

 [[ 61  73  78]
  [ 61  73  78]
  [ 55  67  72]
  ...
  [ 92  88  66]
  [ 86  87  64]
  [ 86  87  64]]

 [[ 64  71  77]
  [ 62  69  75]
  [ 62  69  75]
  ...
  [ 89  84  66]
  [ 89  85  63]
  [ 90  86  64]]

 [[ 57  69  72]
  [ 58  71  73]
  [ 57  69  72]
  ...
  [ 91  82  68]
  [ 91  83  66]
  [ 91  83  66]]]
[[246 139 272 272]]
1
[[[ 76  94  86]
  [ 76  94  86]
  [ 79  93  91]
  ...
  [100 116 109]
  [106 115 109]
  [106 115 109]]

 [[ 78  95  92]
  [ 78  95  92]
  [ 82  97  94]
  ...
  [104 113 112]
  [105 113 107]
  [106 115 109]]

 [[ 85  99  97]
  [ 86 100  98]
  [ 86 100  98]
  ...
  [106 113 112]
  [104 113 112]
  [104 113 112]]

 ...

 [[ 58  

[[251 142 261 261]]
1
[[[ 95 109 107]
  [ 94 110 103]
  [ 94 110 103]
  ...
  [106 115 109]
  [107 116 110]
  [107 116 110]]

 [[ 95 109 107]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [107 116 110]
  [107 116 110]
  [107 116 110]]

 [[101 111 109]
  [101 111 109]
  [101 111 109]
  ...
  [108 117 111]
  [107 116 110]
  [108 117 111]]

 ...

 [[ 49  58  59]
  [ 47  55  56]
  [ 45  54  55]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 48  56  59]
  [ 47  54  55]
  [ 45  52  53]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 40  55  52]
  [ 45  52  51]
  [ 44  51  50]
  ...
  [228 228 228]
  [228 228 228]
  [229 229 229]]]
[[250 141 265 265]]
1
[[[ 93 103 101]
  [ 94 104 102]
  [ 96 105 104]
  ...
  [104 115 109]
  [104 115 109]
  [104 116 107]]

 [[ 93 107 105]
  [ 94 108 106]
  [ 93 107 105]
  ...
  [107 117 108]
  [107 117 108]
  [106 115 107]]

 [[ 99 109 107]
  [ 99 109 107]
  [100 110 108]
  ...
  [107 117 108]
  [107 117 108]
  [107 117 108]]

 ...

 [[ 45  

[[252 144 261 261]]
1
[[[ 98 113 111]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [109 114 113]
  [109 114 113]
  [108 113 112]]

 [[ 98 113 111]
  [ 98 113 111]
  [100 114 112]
  ...
  [109 114 113]
  [109 114 113]
  [109 114 113]]

 [[100 114 112]
  [100 114 112]
  [100 114 112]
  ...
  [110 115 114]
  [109 114 113]
  [109 114 113]]

 ...

 [[ 43  52  46]
  [ 42  51  45]
  [ 43  52  46]
  ...
  [235 232 226]
  [235 232 226]
  [235 232 226]]

 [[ 42  49  48]
  [ 42  49  48]
  [ 42  51  45]
  ...
  [206 197 185]
  [206 197 185]
  [205 194 180]]

 [[ 42  49  48]
  [ 42  49  48]
  [ 42  51  45]
  ...
  [132 117 101]
  [130 115  99]
  [129 114  98]]]
[[249 143 265 265]]
1
[[[ 97 106 105]
  [100 110 108]
  [101 111 109]
  ...
  [107 116 110]
  [107 114 113]
  [107 114 113]]

 [[ 96 111 108]
  [101 111 109]
  [103 112 111]
  ...
  [107 116 110]
  [107 114 113]
  [107 114 113]]

 [[100 110 108]
  [101 111 109]
  [103 112 111]
  ...
  [107 116 110]
  [107 114 113]
  [107 114 113]]

 ...

 [[ 43  

[[244 139 273 273]]
1
[[[ 80  97  94]
  [ 80  97  94]
  [ 81  95  93]
  ...
  [104 113 112]
  [104 113 112]
  [106 113 112]]

 [[ 88 102 100]
  [ 87 101  99]
  [ 84 102  95]
  ...
  [106 115 109]
  [106 115 109]
  [106 113 112]]

 [[ 89 104 101]
  [ 88 102 100]
  [ 89 104 101]
  ...
  [106 113 112]
  [106 113 112]
  [108 113 112]]

 ...

 [[ 52  64  69]
  [ 53  65  70]
  [ 48  61  64]
  ...
  [104  91  70]
  [104  91  70]
  [104  91  70]]

 [[ 52  64  69]
  [ 47  59  64]
  [ 50  57  63]
  ...
  [100  90  73]
  [100  90  73]
  [ 98  89  68]]

 [[ 51  64  66]
  [ 46  59  61]
  [ 45  58  60]
  ...
  [ 96  90  68]
  [ 96  90  68]
  [ 96  87  66]]]
[[251 143 265 265]]
1
[[[ 96 111 108]
  [ 96 111 108]
  [ 97 112 109]
  ...
  [107 114 113]
  [107 116 110]
  [106 115 109]]

 [[ 97 112 109]
  [ 98 113 111]
  [ 98 113 111]
  ...
  [107 116 110]
  [107 116 110]
  [107 116 110]]

 [[ 97 112 109]
  [104 113 112]
  [103 112 111]
  ...
  [106 117 111]
  [107 116 110]
  [107 116 110]]

 ...

 [[ 45  

[[250 144 261 261]]
1
[[[ 97 106 105]
  [100 110 108]
  [ 97 112 109]
  ...
  [109 114 113]
  [109 114 113]
  [109 115 110]]

 [[ 99 109 107]
  [100 110 108]
  [103 112 111]
  ...
  [110 115 114]
  [110 115 114]
  [110 116 111]]

 [[ 99 109 107]
  [101 111 109]
  [103 112 111]
  ...
  [110 115 114]
  [110 115 114]
  [110 116 111]]

 ...

 [[ 45  55  54]
  [ 42  52  50]
  [ 44  51  50]
  ...
  [229 229 229]
  [230 230 230]
  [230 230 230]]

 [[ 49  56  55]
  [ 44  51  50]
  [ 44  51  50]
  ...
  [235 231 227]
  [235 231 227]
  [235 232 226]]

 [[ 47  56  55]
  [ 42  52  50]
  [ 46  51  50]
  ...
  [211 189 179]
  [213 191 181]
  [201 174 165]]]
[[251 141 264 264]]
1
[[[ 93 107 105]
  [ 93 107 105]
  [ 93 107 105]
  ...
  [108 113 112]
  [108 113 112]
  [106 113 112]]

 [[ 93 110 107]
  [ 93 110 107]
  [ 93 110 107]
  ...
  [109 114 113]
  [109 114 113]
  [108 113 112]]

 [[ 93 110 107]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [109 114 113]
  [109 114 113]
  [109 114 113]]

 ...

 [[ 44  

1
[[[ 93 107 105]
  [ 93 107 105]
  [ 91 107 105]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 92 109 106]
  [ 93 110 107]
  [ 93 110 107]
  ...
  [108 114 109]
  [108 114 109]
  [108 114 109]]

 [[ 96 111 108]
  [ 96 111 108]
  [ 97 112 109]
  ...
  [109 115 110]
  [108 114 109]
  [108 115 107]]

 ...

 [[ 49  59  57]
  [ 47  56  55]
  [ 47  55  54]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 49  56  55]
  [ 47  55  54]
  [ 45  52  51]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[ 47  54  55]
  [ 45  52  53]
  [ 44  51  50]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]]
[[250 139 265 265]]
1
[[[ 80  94  92]
  [ 81  95  93]
  [ 86  96  94]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 85  99  97]
  [ 85  99  97]
  [ 90  99  98]
  ...
  [108 114 109]
  [108 114 109]
  [106 115 109]]

 [[ 93 103 101]
  [ 96 105 104]
  [ 93 107 105]
  ...
  [107 116 110]
  [107 116 110]
  [106 115 109]]

 ...

 [[ 48  57  56]
  [ 45  55  

1
[[[ 90  99  98]
  [ 91 101  99]
  [ 88 102 100]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 93 103 101]
  [ 96 105 104]
  [ 93 107 105]
  ...
  [106 115 107]
  [106 115 107]
  [106 115 107]]

 [[ 96 105 104]
  [ 98 107 106]
  [ 95 109 107]
  ...
  [108 115 107]
  [108 115 107]
  [108 115 107]]

 ...

 [[ 44  58  56]
  [ 40  55  52]
  [ 42  53  47]
  ...
  [228 215 208]
  [228 214 209]
  [227 213 208]]

 [[ 51  57  59]
  [ 46  53  54]
  [ 45  54  48]
  ...
  [145 119 108]
  [140 119 106]
  [139 118 105]]

 [[ 50  59  60]
  [ 47  55  56]
  [ 45  52  51]
  ...
  [126 108  86]
  [125 106  86]
  [125 106  86]]]
[[249 139 266 266]]
1
[[[ 82  97  94]
  [ 83  98  95]
  [ 85  99  97]
  ...
  [106 115 109]
  [106 115 109]
  [106 115 109]]

 [[ 87 103  96]
  [ 89 105  98]
  [ 90 106  99]
  ...
  [106 115 109]
  [106 115 109]
  [108 115 107]]

 [[ 93 107 105]
  [ 93 107 105]
  [ 94 108 106]
  ...
  [106 115 109]
  [106 115 109]
  [108 114 109]]

 ...

 [[ 44  54  52]
  [ 42  52  

[[256 153 266 266]]
1
[[[ 82  97  94]
  [ 82  97  94]
  [ 82  97  94]
  ...
  [106 113 112]
  [106 115 109]
  [106 115 109]]

 [[ 89  98  97]
  [ 89  98  97]
  [ 86 100  98]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 [[ 94 104 102]
  [ 94 104 102]
  [ 91 106 104]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 ...

 [[ 46  51  50]
  [ 46  51  50]
  [ 45  50  49]
  ...
  [228 228 228]
  [228 228 228]
  [228 228 228]]

 [[ 45  50  49]
  [ 45  50  49]
  [ 44  50  45]
  ...
  [228 228 228]
  [228 228 228]
  [228 228 228]]

 [[ 45  50  49]
  [ 45  50  49]
  [ 44  50  45]
  ...
  [230 230 230]
  [230 232 227]
  [230 232 227]]]
[[264 157 258 258]]
1
[[[ 94 104 102]
  [ 93 103 101]
  [ 89 104 101]
  ...
  [106 115 109]
  [108 114 109]
  [108 114 109]]

 [[ 95 109 107]
  [ 95 109 107]
  [ 95 109 107]
  ...
  [108 115 107]
  [108 115 107]
  [108 115 107]]

 [[ 97 112 109]
  [ 97 112 109]
  [ 97 112 109]
  ...
  [108 115 107]
  [112 114 107]
  [112 114 107]]

 ...

 [[ 46  

[[259 154 269 269]]
1
[[[ 93 109 109]
  [ 93 109 109]
  [ 93 109 109]
  ...
  [106 115 109]
  [104 113 112]
  [104 113 112]]

 [[ 93 110 107]
  [ 93 109 109]
  [ 93 109 109]
  ...
  [103 114 107]
  [103 112 111]
  [104 113 112]]

 [[ 89 106 104]
  [ 91 107 105]
  [ 91 107 105]
  ...
  [104 113 112]
  [104 113 112]
  [104 113 112]]

 ...

 [[ 44  51  50]
  [ 43  50  49]
  [ 43  50  49]
  ...
  [240 222 200]
  [227 210 187]
  [194 177 155]]

 [[ 44  51  50]
  [ 42  49  48]
  [ 42  49  48]
  ...
  [169 144 132]
  [168 138 125]
  [152 123 109]]

 [[ 42  49  48]
  [ 41  50  49]
  [ 41  50  49]
  ...
  [119  98  74]
  [118  96  74]
  [118  96  74]]]
[[262 153 255 255]]
1
[[[ 87 101  99]
  [ 88 102 100]
  [ 88 102 100]
  ...
  [104 113 112]
  [105 114 113]
  [105 116 110]]

 [[ 85  99  97]
  [ 85  99  97]
  [ 86 100  98]
  ...
  [100 114 112]
  [100 114 112]
  [104 113 112]]

 [[ 87 101  99]
  [ 87 101  99]
  [ 87 101  99]
  ...
  [106 113 112]
  [106 113 112]
  [106 113 112]]

 ...

 [[ 47  

[[237 142 274 274]]
1
[[[ 95 109 107]
  [ 95 109 107]
  [ 95 109 107]
  ...
  [101 111 109]
  [101 111 109]
  [103 112 106]]

 [[ 95 109 107]
  [ 95 109 107]
  [ 95 109 107]
  ...
  [103 112 111]
  [103 112 111]
  [ 98 115 107]]

 [[ 95 109 107]
  [ 95 109 107]
  [ 94 108 106]
  ...
  [107 116 110]
  [106 115 109]
  [106 115 109]]

 ...

 [[ 59  72  81]
  [ 59  72  81]
  [ 60  73  82]
  ...
  [228 228 228]
  [228 228 228]
  [228 228 228]]

 [[ 57  70  79]
  [ 59  69  79]
  [ 59  69  79]
  ...
  [230 230 230]
  [230 230 230]
  [230 230 230]]

 [[ 52  65  74]
  [ 54  66  71]
  [ 54  66  71]
  ...
  [237 233 224]
  [237 233 224]
  [237 233 224]]]
[[239 144 270 270]]
1
[[[ 95 109 107]
  [ 93 107 105]
  [ 93 107 105]
  ...
  [104 115 109]
  [104 115 109]
  [105 116 110]]

 [[ 87 104 101]
  [ 89 104 101]
  [ 89 104 101]
  ...
  [107 114 113]
  [107 114 113]
  [105 114 113]]

 [[ 86 100  98]
  [ 85  99  97]
  [ 87 101  99]
  ...
  [105 116 110]
  [105 116 110]
  [106 116 114]]

 ...

 [[ 59  

-1